#!/bin/sh
# postinst script for backle

set -e

if [ "$1" = "configure" ]; then

	mkdir -p /etc/apache2/conf-available
	ln -sf ../../backle/backle-gforge.conf /etc/apache2/conf-available/backle-gforge.conf

	COMMON_STATE=$(dpkg-query -f '${Status}' -W 'apache2.2-common' 2>/dev/null | awk '{print $3}' || true)

        if [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
		[ -d /etc/apache2/conf.d/ ] && [ ! -L /etc/apache2/conf.d/backle-gforge.conf ] && ln -s ../conf-available/backle-gforge.conf /etc/apache2/conf.d/backle-gforge.conf
                invoke-rc.d apache2 reload 3>/dev/null || true
	fi

        /usr/share/gforge/bin/register-plugin backle 'Backle'
fi

#DEBHELPER#

exit 0
