#!/bin/sh
# postrm script for gforge-backle-plugin

set -e

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
        COMMON_STATE=$(dpkg-query -f '${Status}' -W 'apache2.2-common' 2>/dev/null | awk '{print $3}' || true)

        if [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
                rm -f /etc/apache2/conf.d/backle-gforge.conf
	        rm -f /etc/apache2/conf-available/backle-gforge.conf
	        /etc/init.d/apache2 reload 3>/dev/null || true
        fi

        /usr/share/gforge/bin/unregister-plugin backle
fi




#DEBHELPER#

exit 0


